from enum import Enum


class Gen1Error(Enum):
    """lemonbeat.error for Gen1 watering computer and sensor1 devices."""

    NONE = 0
    OVERTEMPERATURE = 1  # DEPRECATED, not checked anymore
    EEPROM = 2
    BROWN_OUT = 3

    def __str__(self) -> str:
        return self.name.lower()


class Sensor2Error(Enum):
    """lemonbeat.error for sensor2 (capacitive moisture sensor) devices."""

    NONE = 0
    EEPROM = 1

    def __str__(self) -> str:
        return self.name.lower()


class PowerError(Enum):
    """lemonbeat.error for power adapter devices."""

    NONE = 0
    TIMER_CANCELLED = 1  # unused error
    EEPROM = 2

    def __str__(self) -> str:
        return self.name.lower()


class IC24Error(Enum):
    """lemonbeat.error for IC24 (Gen2 irrigation controller) devices."""

    NONE = 0
    VOLTAGE_DROP = 1
    POWER_SUPPLY = 2
    SECONDARY_MCU = 3
    EEPROM = 4

    def __str__(self) -> str:
        return self.name.lower()


class Gen1ValveError(Enum):
    """lemonbeat.valve_error_1 for Gen1 watering computer devices."""

    NONE = 0
    VALVE_BROKEN = 1
    FROST_PREVENTS_STARTING = 2
    LOW_BATTERY_PREVENTS_STARTING = 3
    VALVE_POWER_SUPPLY_FAILED = 4

    def __str__(self) -> str:
        return self.name.lower()


class IC24ValveError(Enum):
    """actuator.error (valve error) for IC24 (Gen2 irrigation controller) devices."""

    NONE = 0
    EXCEEDED_VALVES_LIMIT = 1
    VALVE_NOT_CONNECTED = 2
    EXCEEDED_CURRENT = 3
    EXCEEDED_TOTAL_CURRENT = 4
    MASTER_VALVE = 5
    DURATION_TOO_SHORT = 6

    def __str__(self) -> str:
        return self.name.lower()


class DeviceErrorCode(Enum):
    """device.error_code values (reported as an array) for all devices."""

    LOW_BATTERY_POWER = 1
    EXTERNAL_POWER_SUPPLY_OFF = 2
    GPS_MODULE_FAILURE = 3
    LOW_RECEIVED_SIGNAL_STRENGTH = 4
    OUT_OF_MEMORY = 5
    SMS_FAILURE = 6
    IP_CONNECTIVITY_FAILURE = 7
    PERIPHERAL_MALFUNCTION = 8

    def __str__(self) -> str:
        return self.name.lower()


class MowerLastErrorCode(Enum):
    """lemonbeat.last_error_code for Gen1 mower devices."""

    NO_MESSAGE = 0
    OUTSIDE_WORKING_AREA = 1
    NO_LOOP_SIGNAL = 2
    WRONG_LOOP_SIGNAL = 3
    LOOP_SENSOR_PROBLEM_FRONT = 4
    LOOP_SENSOR_PROBLEM_REAR = 5
    LEFT_LOOP_SENSOR_DEFECT = 6
    RIGHT_LOOP_SENSOR_DEFECT = 7
    WRONG_PIN_CODE = 8
    TRAPPED = 9
    UPSIDE_DOWN = 10
    LOW_BATTERY = 11
    EMPTY_BATTERY = 12
    NO_DRIVE = 13
    TEMPORARY_LIFTED = 14
    LIFTED = 15
    STUCK_IN_CHARGING_STATION = 16
    CHARGING_STATION_BLOCKED = 17
    COLLISION_SENSOR_PROBLEM_REAR = 18
    COLLISION_SENSOR_PROBLEM_FRONT = 19
    WHEEL_MOTOR_BLOCKED_RIGHT = 20
    WHEEL_MOTOR_BLOCKED_LEFT = 21
    WHEEL_DRIVE_PROBLEM_RIGHT = 22
    WHEEL_DRIVE_PROBLEM_LEFT = 23
    CUTTING_MOTOR_DRIVE_DEFECT = 24
    CUTTING_SYSTEM_BLOCKED = 25
    INVALID_SUB_DEVICE_COMBINATION = 26
    SETTINGS_RESTORED = 27
    UNSOLVED_NVRAM_FAIL = 28
    TOO_STEEP_SLOPE = 29
    CHARGING_SYSTEM_PROBLEM = 30
    FAILED_START_STOP_BUTTON = 31
    TILT_SENSOR_PROBLEM = 32
    MOWER_TILTED = 33
    CUT_MEANS_TURN_OFF_IN_SLOPE = 34
    WHEEL_MOTOR_OVERLOADED_RIGHT = 35
    WHEEL_MOTOR_OVERLOADED_LEFT = 36
    CHARGING_CURRENT_TOO_HIGH = 37
    TEMPORARY_PROBLEM = 38
    CUTTING_MEANS_OVERLOADED = 39
    LIMITED_CUTTING_HEIGHT_RANGE = 40
    CUTTING_HEIGHT_DRIFT = 41
    CUTTING_HEIGHT_LIMITED = 42
    CUTTING_HEIGHT_DRIVE_SYSTEM = 43
    HIGH_CUTTING_HEIGHT_CURRENT = 44
    RUNNING_IN_OPPOSITE_DIRECTION = 45
    CUTTING_HEIGHT_BLOCKED = 46
    UNDEFINED_CUT_HEIGHT_PROBLEM = 47
    PROBLEMS_WHEN_COM_WITH_CS = 48
    ERROR_REPORTED_FROM_US = 49
    GUIDE_1_NOT_FOUND = 50
    GUIDE_2_NOT_FOUND = 51
    GUIDE_3_NOT_FOUND = 52
    GPS_TRACKER_MODULE_ERROR = 53
    WEAK_GPS_MAP_SIGNAL = 54
    FOLLOW_BOUNDARY_AROUND_DETECT = 55
    GUIDE_CALIBRATION_ACCOMPLISHED = 56
    GUIDE_CALIBRATION_FAILED = 57
    BAT_TYPE_SENSOR_NOK_FOR_BAT_A = 58
    BAT_TYPE_SENSOR_NOK_FOR_BAT_B = 59
    BAT_TEMP_SENSOR_NOK_FOR_BAT_A = 60
    BAT_TEMP_SENSOR_NOK_FOR_BAT_B = 61
    TEMPORARY_BATTERY_PROBLEM = 62
    TOO_HIGH_LOW_TEMP_FOR_BAT_B = 63
    TOO_LOW_VOLTAGE_FOR_BAT_A = 64
    TOO_LOW_VOLTAGE_ON_BATTERY_B = 65
    BATTERY_PROBLEM = 66
    TOO_MANY_BATTERIES = 67
    ALARM_MOWER_SWITCHED_OFF = 69
    ALARM_MOWER_STOPPED = 70
    ALARM_MOWER_LIFTED = 71
    ALARM_MOWER_TILTED = 72
    ALARM_MOTION_OF_MOWER = 73
    ALARM_OUTSIDE_GEOFENCE = 74
    CS_COMMUNICATION_OK = 75
    CONNECTION_NOT_CHANGED = 76
    COM_BOARD_NOT_AVAILABLE = 77
    SLIPPED = 78
    INVALID_BATTERY_COMBINATION = 79
    IMBALANCED_CUTTING_DISC = 80
    SAFETY_FUNCTION_FAULTY = 81
    REAR_RIGHT_WHEEL_MOTOR_BLOCKED = 82
    REAR_LEFT_WHEEL_MOTOR_BLOCKED = 83
    REAR_RIGHT_WHEEL_DRIVE_SYSTEM = 84
    REAR_LEFT_WHEEL_DRIVE_SYSTEM = 85
    REAR_RIGHT_WHEEL_OVERLOADED = 86
    REAR_LEFT_WHEEL_OVERLOADED = 87
    INVALID_VALUES_FROM_ANGULAR_SENSOR = 88
    INVALID_SETUP_OF_NODES = 89
    NO_POWER_IN_CHARGING_STATION = 90
    INVALID_VALUES_FROM_SWITCH_CORD_SENSOR = 91
    PROGRAMMED_WORKING_AREA_INVALID = 92
    HI_RES_POSITIONING_NO_VALID_POSITION = 93
    REFERENCE_STATION_COMMUNICATION_DISTURBED = 94
    CUTTING_DECK_FOLDING_MECHANISM_NOT_LOCKED = 95
    ULTRASONIC_SENSOR_1_FAIL = 98
    ULTRASONIC_SENSOR_2_FAIL = 99
    ULTRASONIC_SENSOR_3_FAIL = 100
    ULTRASONIC_SENSOR_4_FAIL = 101
    CUTTING_MOTOR_1_FAULT = 102
    CUTTING_MOTOR_2_FAULT = 103
    CUTTING_MOTOR_3_FAULT = 104
    LIFT_SENSOR_DEFECT = 105
    COLLISION_SENSOR_DEFECT = 106
    DOCKING_SENSOR_DEFECT = 107
    CUTTING_DECK_RELEASE_LEVER_SENSOR_DEFECT = 108
    LOOP_SENSORS_DEFECT = 109
    MOWER_JAMMED_OR_COLLISION_SENSOR_DEFECT = 110
    HI_RES_POSITIONING_NO_CONFIRMED_POSITION = 111
    MAJOR_IMBALANCE_IN_CUTTING_DISK = 112
    WORKING_AREA_TOO_MANY_WAYPOINTS = 113
    MOBILE_LOOP_FAULT = 119
    MOWER_FAILED_TO_REACH_DESTINATION_ERROR = 123
    MOWER_FAILED_TO_REACH_DESTINATION_WARNING = 124
    BATTERY_NEAR_END_OF_LIFE = 126
    BMS_DISCHARGE_FET_ERROR = 127
    EDGEMOTOR_BLOCKED = 129
    EPOS_ACCESSORY_MISSING = 132
    INVALID_SW_CONFIGURATION = 134
    ERROR_REPORTED_FROM_RADAR = 135
    REFERENCE_STATION_OR_CS_MOVED = 136
    NO_CORRECTION_DATA_AVAILABLE = 145
    INVALID_CORRECTION_DATA = 146

    def __str__(self) -> str:
        return self.name.lower()
